name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    repository_dispatch:
      types: [update-docs]

jobs:
  build:
    name: Build Docusaurus with Versioning
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the documentation repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Step 2: Clone the `esscrypt/histori-rest-api` repository
      - name: Clone histori-rest-api repository
        run: git clone https://github.com/esscrypt/histori-rest-api.git

      # Step 3: Extract version from `package.json`
      - name: Get version from package.json
        id: get_version
        run: |
          version=$(jq -r '.version' histori-rest-api/package.json)
          echo "Version from package.json: $version"
          echo "new_version=$version" >> $GITHUB_ENV

      # Step 4: Copy the `swagger.json` file
      - name: Copy swagger.json
        run: cp histori-rest-api/swagger.json ./swagger.json

      # Step 5: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 6: Generate the API documentation with the version from package.json
      - name: Generate API documentation
        run: npm run docusaurus docs:version ${{ env.new_version }}

      # Step 7: Build the Docusaurus website
      - name: Build website
        run: npm run build

      # Step 8: Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
