name: Deploy Docusaurus site

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install latest Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # This will automatically use the latest Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Deploy to GitHub Pages
        run: USE_SSH=true npx docusaurus deploy
        env:
          GIT_USER: ${{ secrets.GIT_USER }}  # Set up in Secrets
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT instead of default GITHUB_TOKEN }}
